---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ openio_nfs_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install
...
